### ISSUE TITLE
Suspend member command sometimes crashes with unknown interaction error

### ISSUE THREAD

**Issue by ewang2002** [ewang2002/OneLifeBot#41]
```
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (C:\Users\user\desktop\projects\onerealm\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\user\desktop\projects\onerealm\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async CommandInteraction.reply (C:\Users\user\desktop\projects\onerealm\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:99:5)
    at async SuspendMember.run (C:\Users\user\desktop\projects\onerealm\out\commands\punishments\SuspendMember.js:104:9)
    at async slashCommandHandler (C:\Users\user\desktop\projects\onerealm\out\events\InteractionEvent.js:106:9)
    at async onInteractionEvent (C:\Users\user\desktop\projects\onerealm\out\events\InteractionEvent.js:148:9) {
  method: 'post',
  path: '/interactions/929899447335387176/aW50ZXJhY3Rpb246OTI5ODk5NDQ3MRqQVZSM3ZxTG9lYzJQemUyOFFFNGtEMEhjUm9RNV5TEphWXpCMjVUa09FSjRVc2U3QUd2dTZJaFlycXd4cmtaUUVaZ1VQbko1WUUyTlQz/callback',
  code: 10062,
  httpStatus: 404,
  requestData: {
    json: {
      type: 4,
      data: {
        content: undefined,
        tts: false,
        nonce: undefined,
        embeds: [
          {
            title: 'Suspension Issued.',
            type: 'rich',
            description: '@sjkd23#0469 has been suspended successfully.',
            url: null,
            timestamp: 2022-01-10T00:48:38.130Z,
            color: 15548997,
            fields: [Array],
            thumbnail: null,
            image: null,
            author: [Object],
            footer: null
          }
        ],
        components: undefined,
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: undefined,
        message_reference: undefined,
        attachments: undefined,
        sticker_ids: undefined
      }
    },
    files: []
  }
}
```

**Comment by ewang2002** [comment]
Note that [this line](https://github.com/ewang2002/OneLifeBot/blob/5bb95c1ed8833066766208c9b4a66743dc98a5b8/src/commands/punishments/SuspendMember.ts#L118) is the issue. Although I'm not sure why there's an "unknown interaction" error when the interaction is a command interaction -- one that is needed to invoke the command to begin with

**Comment by dmansdman** [comment]
Potentially a timeout issue due to the 3s limitation of interaction replies.  Used DeferReply() for all punishment commands to increase time to 15 minutes, in hopes of resolving issue.

**Comment by ewang2002** [comment]
Fixed
