### ISSUE TITLE
Error occurring with interaction already sent/deferred when trying to reconnect people to VC

### ISSUE THREAD

**Issue by ewang2002** [ewang2002/OneLifeBot#44]
```
C:\Users\user\desktop\projects\onerealm\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:180
    if (this.deferred || this.replied) throw new Error('INTERACTION_ALREADY_REPLIED');
                                             ^

Error [INTERACTION_ALREADY_REPLIED]: The reply to this interaction has already been sent or deferred.
    at ButtonInteraction.deferUpdate (C:\Users\user\desktop\projects\onerealm\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:180:46)
    at RaidInstance.interactionEventFunction (C:\Users\user\desktop\projects\onerealm\out\instances\RaidInstance.js:1873:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async onInteractionEvent (C:\Users\user\desktop\projects\onerealm\out\events\InteractionEvent.js:207:9) {
  [Symbol(code)]: 'INTERACTION_ALREADY_REPLIED'
}
```

Error occurring [here](https://github.com/ewang2002/OneLifeBot/blob/1bcf8eb259cbe12b2335419485337ad5294b6e06/src/instances/RaidInstance.ts#L2215)

**Comment by dmansdman** [comment]
Issue in RaidInstance.ts, interactionEventFunction() - line 2189.  Missing return statement after member is reconnected.  Will be part of next PR.
